routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\User;
use App\Permisos\Models\Role;
use App\Permisos\Models\Permission;
use Illuminate\Support\Facades\Gate;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
  if(Auth::guest())
    return view('auth.login');                   
  else
    return view('home');

});

Route::get('/remisiones', function () {
  return view('home_remisiones');
});


Auth::routes();

Route::get('/logout', function () {
  Auth::logout();
  return redirect('/');
});

Route::get('/home', 'HomeController@index')->name('home');


Route::resource('/role', 'RoleController')->names('role');

Route::resource('/remisiones/remisiones', 'RemisionesController')->names('remisiones');

Route::resource('/remisiones/clientes', 'ClientesRemisionController')->names('clientesRemisiones');
Route::resource('/remisiones/productos', 'ProductosRemisionController')->names('productosRemisiones');
Route::resource('/remisiones/conductores', 'ConductoresRemisionController')->names('conductoresRemisiones');
Route::resource('/remisiones/parametros', 'ParametrosRemisionController')->names('parametrosRemisiones');



Route::get('/remisiones/keyup/clientes/{valor?}', 'ClientesRemisionController@keyup_cliente');
Route::get('/remisiones/keyup/productos/{valor?}', 'ProductosRemisionController@keyup_producto');
Route::get('/remisiones/keyup/conductores/{valor?}', 'ConductoresRemisionController@keyup_conductores');

/* relleno de informacion en formulario remisiones segun cliente*/
Route::get('/remisiones/onchange/cliente/{valor?}', 'RemisionesController@onchange_cliente');

Route::get('/remisiones/onchange/producto_tabla/{valor?}', 'RemisionesController@onchange_productos');

Route::get('/remisiones/onchange/conductor/{atributo?}/{informacion?}', 'RemisionesController@onchange_conductor');

Route::get('/remisiones/remisiones/exportar/pdf/{atributo?}', 'RemisionesController@exportar_pdf')->name('remisiones.pdf');
Route::get('/remisiones/remisiones/imprimir/{atributo?}', 'RemisionesController@imprimir')->name('remisiones.imprimir');









/*

Route::get('/generate/csv/{fechaInicial?}/{fechaFinal?}/{conferencia?}/{asociado?}/{regional?}', 'ReportesController@exportCSVTodo');
Route::post('/reportes/exportTodoPdf', 'ReportesController@exportPDFTodo')->name('reportes.exportTodoPdf');

*/
Route::post('/reportes/generatemensajes', 'ReportesController@generatemensajes')->name('reportes.generatemensajes');
Route::post('/reportes/export/mensajes', 'ReportesController@exportMensajesCSV')->name('reportes.export.mensajes');
Route::post('/reportes/export/mensajespdf', 'ReportesController@exportMensajesPDF')->name('reportes.export.mensajespdf');




Route::resource('/user', 'UserController', ['except' => [
        'create', 'store']])->names('user');

resources/views/clientes/crear.blade.php
@extends('layouts.app')

@section('content')
<div class="content " >
    <div class="container-fluid" style="background-color: white; padding-top: 10px;">
        <div class="row">
            <div class="col-md-12">
              <div class="card card-plain">
                <div class="card-header card-header-primary">
                  <h3 class="card-title mt-0">Registrar cliente</h3>
                </div>

                <div class="card-body">
                    @include('custom.message')
                  <div class="table-responsive">
                    
                    <form action="{{ route('clientesRemisiones.store') }}" method="POST">
                        @csrf
                        @method('POST')

                        <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="row">
                                <div class="col-12 col-sm-6 col-md-6 col-lg-6">
                                    <label style="padding-bottom: 5px;"><b>(*) Tipo de identificación:</b></label>
                                    <select class="form-control" name="tipo_identificacion">
                                        <option value="" selected="">Seleccione un tipo de identificación</option>
                                        @foreach($tipo_identificacion as $tipo)
                                        <option value="{{ $tipo->id_tipo }}">{{ $tipo->descripcion_tipo }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="col-12 col-sm-6 col-md-6 col-lg-6">
                                    <label style="padding-bottom: 5px;"><b>(*) Número de identificación:</b></label>
                                  <input type="text" class="form-control" placeholder="" name="identificacion" value="{{ old('identificacion') }}">
                                </div>
                            </div>
                        </div>

                        <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="row">
                                <div class="col-12 col-sm-6 col-md-6 col-lg-6">
                                    <label style="padding-bottom: 5px;"><b>(*) Primer nombre:</b></label>
                                  <input type="text" class="form-control" placeholder="" name="primer_nombre" value="{{ old('primer_nombre') }}">
                                </div>
                                <div class="col-12 col-sm-6 col-md-6 col-lg-6">
                                    <label style="padding-bottom: 5px;"><b>Segundo nombre:</b></label>
                                  <input type="text" class="form-control" placeholder="" name="segundo_nombre" value="{{ old('segundo_nombre') }}">
                                </div>
                            </div>
                        </div>

                        <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="row">
                                <div class="col-12 col-sm-6 col-md-6 col-lg-6">
                                    <label style="padding-bottom: 5px;"><b>(*) Primer apellido</b></label>
                                  <input type="text" class="form-control" placeholder="" name="primer_apellido" value="{{ old('primer_apellido') }}">
                                </div>
                                <div class="col-12 col-sm-6 col-md-6 col-lg-6">
                                    <label style="padding-bottom: 5px;"><b> Segundo apellido:</b></label>
                                  <input type="text" class="form-control" placeholder="" name="segundo_apellido" value="{{ old('segundo_apellido') }}">
                                </div>
                            </div>
                        </div>

                        <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
                            <label style="padding-bottom: 5px;"><b>(*) Direcci&oacute;n:</b></label>
                            <input type="text" class="form-control" placeholder="" name="direccion" value="{{ old('direccion') }}">
                        </div>

                        <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
                            <label style="padding-bottom: 5px;"><b>(*) Ciudad</b></label>
                            <input type="text" class="form-control" placeholder="" name="ciudad" value="{{ old('ciudad') }}">
                        </div>

                        <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="row">
                                <div class="col-12 col-sm-6 col-md-6 col-lg-6">
                                    <label style="padding-bottom: 5px;"><b>Telefono fijo</b></label>
                                  <input type="text" class="form-control" placeholder="" name="telefono_fijo" value="{{ old('telefono_fijo') }}">
                                </div>
                                <div class="col-12 col-sm-6 col-md-6 col-lg-6">
                                    <label style="padding-bottom: 5px;"><b>(*) Celular:</b></label>
                                  <input type="text" class="form-control" placeholder="" name="celular" value="{{ old('celular') }}">
                                </div>
                            </div>
                        </div>

                        <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="row">
                                <div class="col-12 col-sm-6 col-md-6 col-lg-6">

                                </div>
                                <div class="col-12 col-sm-6 col-md-6 col-lg-6">
                                    <label style="padding-bottom: 5px;"><b> Celular 2:</b></label>
                                  <input type="text" class="form-control" placeholder="" name="celular_2" value="{{ old('celular_2') }}">
                                </div>
                            </div>
                        </div>

                        <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
                            <label style="padding-bottom: 5px;"><b>(*) Correo electronico</b></label>
                            <input type="email" class="form-control" placeholder="" name="correo" value="{{ old('correo') }}">
                        </div>

                        <div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
                            <label style="padding-bottom: 5px;"><b>(*) Estado cliente</b></label>
                            <select class="form-control" name="estado">
                                <option value="1">Activo</option>
                                <option value="0">Inactivo</option>
                            </select>
                        </div>

                        <div class="botones col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12" style="margin-top: 40px; margin-bottom: 20px;">
                            <center>
                                <button class="btn btn-danger" type="button">
                                    Cancelar registro
                                </button>
                                <button class="btn btn-success" type="submit">
                                    Registrar cliente
                                </button>
                            </center>
                        </div>

                    </form>
                  </div>
                </div>

              </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/clientes/edicion.blade.php
@foreach($clientes as $cliente)
<div class="container">
	 @include('custom.parameters')

	 {!! Form::open(['route' => array('clientesRemisiones.update', $cliente->id), 'files' => true]) !!}

		@csrf
		@method('PUT')
	
		<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
			<div class="row">
				<div class="col-12 col-sm-6 col-md-6 col-lg-6">
					<label style="padding-bottom: 5px;"><b>(*) Tipo de identificación:</b></label>
					<select class="form-control" name="tipo_identificacion" readonly="" >
						@foreach($tipo_identificacion as $tipo)
							@if($cliente->tipo_id_cliente == $tipo->id_tipo)
								<option value="{{ $tipo->id_tipo }}" selected="">{{ $tipo->descripcion_tipo }}</option>
							@else
								<option value="{{ $tipo->id_tipo }}">{{ $tipo->descripcion_tipo }}</option>
							@endif
						@endforeach
					</select>
				</div>
				<div class="col-12 col-sm-6 col-md-6 col-lg-6">
					<label style="padding-bottom: 5px;"><b>(*) Número de identificación:</b></label>
					<input type="text" class="form-control" placeholder="" name="identificacion" value="{{ $cliente->identificacion }}"  readonly="" />
				</div>
			</div>
		</div>

		<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
			<div class="row">
				<?php 
					$array_nombre = explode(" ", $cliente->nombres_cliente);
				?>
				<div class="col-12 col-sm-6 col-md-6 col-lg-6">
					<label style="padding-bottom: 5px;"><b>(*) Primer nombre:</b></label>
					<input type="text" class="form-control" placeholder="" name="primer_nombre" value="{{ $array_nombre[0] }}" >
				</div>
				<div class="col-12 col-sm-6 col-md-6 col-lg-6">
					<label style="padding-bottom: 5px;"><b>Segundo nombre:</b></label>
					<input type="text" class="form-control" placeholder="" name="segundo_nombre" value="{{ $array_nombre[1] }}" >
				</div>
			</div>
		</div>

		<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
			<div class="row">
				<?php 
					$array_apellido = explode(" ", $cliente->apellidos_cliente);
				?>
				<div class="col-12 col-sm-6 col-md-6 col-lg-6">
					<label style="padding-bottom: 5px;"><b>(*) Primer apellido</b></label>
					<input type="text" class="form-control" placeholder="" name="primer_apellido" value="{{ $array_apellido[0] }}" >
				</div>
				<div class="col-12 col-sm-6 col-md-6 col-lg-6">
					<label style="padding-bottom: 5px;"><b> Segundo apellido:</b></label>
					<input type="text" class="form-control" placeholder="" name="segundo_apellido" value="{{ $array_apellido[1] }}" >
				</div>
			</div>
		</div>

		<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
			<label style="padding-bottom: 5px;"><b>(*) Direcci&oacute;n:</b></label>
			<input type="text" class="form-control" placeholder="" name="direccion" value="{{ $cliente->direccion_cliente }}" >
		</div>

		<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
			<label style="padding-bottom: 5px;"><b>(*) Ciudad</b></label>
			<input type="text" class="form-control" placeholder="" name="ciudad" value="{{ $cliente->ciudad_cliente }}" >
		</div>

		<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
			<div class="row">
				<div class="col-12 col-sm-6 col-md-6 col-lg-6">
					<label style="padding-bottom: 5px;"><b>Telefono fijo</b></label>
					<input type="text" class="form-control" placeholder="" name="telefono_fijo" value="{{ $cliente->telefono_fijo_cliente }}" >
				</div>
				<div class="col-12 col-sm-6 col-md-6 col-lg-6">
					<label style="padding-bottom: 5px;"><b>(*) Celular:</b></label>
					<input type="text" class="form-control" placeholder="" name="celular" value="{{ $cliente->celular_1_cliente }}" >
				</div>
			</div>
		</div>

		<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
			<div class="row">
				<div class="col-12 col-sm-6 col-md-6 col-lg-6"></div>
				<div class="col-12 col-sm-6 col-md-6 col-lg-6">
					<label style="padding-bottom: 5px;"><b> Celular 2:</b></label>
					<input type="text" class="form-control" placeholder="" name="celular_2" value="{{ $cliente->celular_2_cliente }}" >
				</div>
			</div>
		</div>

		<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
			<label style="padding-bottom: 5px;"><b>(*) Correo electronico</b></label>
			<input type="email" class="form-control" placeholder="" name="correo" value="{{ $cliente->email_cliente }}" >
		</div>
		
		<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
			<label style="padding-bottom: 5px;"><b>(*) Estado cliente</b></label>
			<select class="form-control" name="estado" >
				@if($cliente->estado_cliente == '1')
					<option value="1" selected="">Activo</option>
					<option value="0">Inactivo</option>
				@else
					<option value="1">Activo</option>
					<option value="0" selected="">Inactivo</option>
				@endif
			</select>
		</div>

		<div class="botones col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12" style="margin-top: 40px; margin-bottom: 20px;">
			<center>
				<button class="btn btn-danger" type="button" data-dismiss="modal" aria-label="Close">
					<i class="fas fa-ban"></i> Cancelar actualizacion
				</button>
				<button class="btn btn-success" type="submit">
					<i class="fas fa-sync-alt"></i> Actualizar
				</button>
			</center>
		</div>

	{!! Form::close() !!}
</div>
@endforeach

resources/views/clientes/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content " >
    <div class="container-fluid" style="background-color: white; padding-top: 10px;">
        <div class="row">
            <div class="col-md-12">
              <div class="card card-plain">
                <div class="card-header card-header-primary">
                  <h3 class="card-title mt-0">Modulo de clientes</h3>
                  <p class="card-category">Acá puede ver todos los clientes registrados en el sistema</p>
                </div>
                <div class="card-body">
                    @include('custom.message')
                  <div class="table-responsive">
                    <div class="form-group">
                        <label><b>Búsqueda de clientes...</b></label>
                        <input type="text" class="form-control" id="busqueda_cliente" name="busqueda_cliente" placeholder="Digite nombre, apellido o identificacion del cliente a buscar">
                    </div>
                    <hr style="margin-top: 10px; margin-bottom: 20px;">
                    <table class="table table-hover table-bordered" id="resultado_consulta">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col"><b>Identificacion</b></th>
                                <th scope="col"><b>Nombre</b></th>
                                <th scope="col"><b>Apellido</b></th>
                                <th scope="col"><b>Correo</b></th>
                                <th scope="col"><b>Estado</b></th>
                                <th scope="col" style="text-align: center;" colspan="2"><b>Acciones</b></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $i=1; ?>
                             @foreach($clientes as $cliente)
                             
                             <tr>
                                <td>{{ $i++ }}</td>
                                <td>{{ $cliente->identificacion }}</td>
                                <td>{{ $cliente->nombres_cliente }}</td>
                                <td>{{ $cliente->apellidos_cliente }}</td>
                                <td>{{ $cliente->email_cliente }}</td>
                                @if($cliente->estado_cliente == '1')
                                    <td class="alert alert-success">Activo</td>
                                @else
                                    <td class="alert alert-danger">Inactivo</td>
                                @endif
                                <td style="text-align: center;">
                                    <button type="button" class="btn btn-info btnVer" title="Ver registro" data-id="{{ $cliente->id }}" data-url="{{ route('clientesRemisiones.show', $cliente->id ) }}"><i class="fas fa-eye"></i></button>
                                    <button type="button" class="btn btn-success btnEdicion" title="Editar registro" data-id="{{ $cliente->id }}" data-url="{{ route('clientesRemisiones.edit', $cliente->id ) }}"><i class="far fa-edit"></i></button>
                                </td>
                                <td>
                                    <center>
                                    <form method="POST" action="{{ route('clientesRemisiones.destroy', $cliente->id)}}">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger" title="Eliminar registro">
                                            <i class="fas fa-user-times"></i>
                                        </button>
                                    </form>
                                    </center>
                                </td>
                             </tr>
                             @endforeach
                        </tbody>
                    </table>
                    {{ $clientes->links() }}
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/clientes/keyup.blade.php
<thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col"><b>Identificacion</b></th>
                                <th scope="col"><b>Nombre</b></th>
                                <th scope="col"><b>Apellido</b></th>
                                <th scope="col"><b>Correo</b></th>
                                <th scope="col" style="text-align: center;" colspan="2"><b>Acciones</b></th>
                            </tr>
                        </thead>
                        <tbody>
                             @foreach($clientes as $cliente)
                             <?php $i=1; ?>
                             <tr>
                                <td>{{ $i++ }}</td>
                                <td>{{ $cliente->identificacion }}</td>
                                <td>{{ $cliente->nombres_cliente }}</td>
                                <td>{{ $cliente->apellidos_cliente }}</td>
                                <td>{{ $cliente->email_cliente }}</td>
                                <td style="text-align: center;">
                                    <button type="button" class="btn btn-info btnVer" title="Ver registro" data-id="{{ $cliente->id }}" data-url="{{ route('clientes.show', $cliente->id ) }}"><i class="fas fa-eye"></i></button>
                                    <button type="button" class="btn btn-success btnEdicion" title="Editar registro" data-id="{{ $cliente->id }}" data-url="{{ route('clientes.edit', $cliente->id ) }}"><i class="far fa-edit"></i></button>
                                </td>
                                <td>
                                    <center>
                                    <form method="POST" action="{{ route('clientes.destroy', $cliente->id)}}">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger" title="Eliminar registro">
                                            <i class="fas fa-user-times"></i>
                                        </button>
                                    </form>
                                    </center>
                                </td>
                             </tr>
                             @endforeach
                        </tbody>

resources/views/clientes/ver.blade.php
@foreach($clientes as $cliente)
<div class="container">
	 @include('custom.parameters')
	<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
		<div class="row">
			<div class="col-12 col-sm-6 col-md-6 col-lg-6">
				<label style="padding-bottom: 5px;"><b>(*) Tipo de identificación:</b></label>
				<select class="form-control" name="tipo_identificacion" readonly="" disabled="">
					@foreach($tipo_identificacion as $tipo)
						@if($cliente->tipo_id_cliente == $tipo->id_tipo)
							<option value="{{ $tipo->id_tipo }}" selected="">{{ $tipo->descripcion_tipo }}</option>
						@else
							<option value="{{ $tipo->id_tipo }}">{{ $tipo->descripcion_tipo }}</option>
						@endif
					@endforeach
				</select>
			</div>
			<div class="col-12 col-sm-6 col-md-6 col-lg-6">
				<label style="padding-bottom: 5px;"><b>(*) Número de identificación:</b></label>
				<input type="text" class="form-control" placeholder="" name="identificacion" value="{{ $cliente->identificacion }}" disabled="" />
			</div>
		</div>
	</div>

	<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
		<div class="row">
			<?php 
				$array_nombre = explode(" ", $cliente->nombres_cliente);
			?>
			<div class="col-12 col-sm-6 col-md-6 col-lg-6">
				<label style="padding-bottom: 5px;"><b>(*) Primer nombre:</b></label>
				<input type="text" class="form-control" placeholder="" name="primer_nombre" value="{{ $array_nombre[0] }}" disabled="">
			</div>
			<div class="col-12 col-sm-6 col-md-6 col-lg-6">
				<label style="padding-bottom: 5px;"><b>Segundo nombre:</b></label>
				<input type="text" class="form-control" placeholder="" name="segundo_nombre" value="{{ $array_nombre[1] }}" disabled="">
			</div>
		</div>
	</div>

	<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
		<div class="row">
			<?php 
				$array_apellido = explode(" ", $cliente->apellidos_cliente);
			?>
			<div class="col-12 col-sm-6 col-md-6 col-lg-6">
				<label style="padding-bottom: 5px;"><b>(*) Primer apellido</b></label>
				<input type="text" class="form-control" placeholder="" name="primer_apellido" value="{{ $array_apellido[0] }}" disabled="">
			</div>
			<div class="col-12 col-sm-6 col-md-6 col-lg-6">
				<label style="padding-bottom: 5px;"><b> Segundo apellido:</b></label>
				<input type="text" class="form-control" placeholder="" name="segundo_apellido" value="{{ $array_apellido[1] }}" disabled="">
			</div>
		</div>
	</div>

	<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
		<label style="padding-bottom: 5px;"><b>(*) Direcci&oacute;n:</b></label>
		<input type="text" class="form-control" placeholder="" name="direccion" value="{{ $cliente->direccion_cliente }}" disabled="">
	</div>

	<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
		<label style="padding-bottom: 5px;"><b>(*) Ciudad</b></label>
		<input type="text" class="form-control" placeholder="" name="ciudad" value="{{ $cliente->ciudad_cliente }}" disabled="">
	</div>

	<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
		<div class="row">
			<div class="col-12 col-sm-6 col-md-6 col-lg-6">
				<label style="padding-bottom: 5px;"><b>Telefono fijo</b></label>
				<input type="text" class="form-control" placeholder="" name="telefono_fijo" value="{{ $cliente->telefono_fijo_cliente }}" disabled="">
			</div>
			<div class="col-12 col-sm-6 col-md-6 col-lg-6">
				<label style="padding-bottom: 5px;"><b>(*) Celular:</b></label>
				<input type="text" class="form-control" placeholder="" name="celular" value="{{ $cliente->celular_1_cliente }}" disabled="">
			</div>
		</div>
	</div>

	<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
		<div class="row">
			<div class="col-12 col-sm-6 col-md-6 col-lg-6"></div>
			<div class="col-12 col-sm-6 col-md-6 col-lg-6">
				<label style="padding-bottom: 5px;"><b> Celular 2:</b></label>
				<input type="text" class="form-control" placeholder="" name="celular_2" value="{{ $cliente->celular_2_cliente }}" disabled="">
			</div>
		</div>
	</div>

	<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
		<label style="padding-bottom: 5px;"><b>(*) Correo electronico</b></label>
		<input type="email" class="form-control" placeholder="" name="correo" value="{{ $cliente->email_cliente }}" disabled="">
	</div>
	
	<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
		<label style="padding-bottom: 5px;"><b>(*) Estado cliente</b></label>
		<select class="form-control" name="estado" disabled="">
			@if($cliente->estado_cliente == '1')
				<option value="1" selected="">Activo</option>
				<option value="0">Inactivo</option>
			@else
				<option value="1">Activo</option>
				<option value="0" selected="">Inactivo</option>
			@endif
		</select>
	</div>

</div>
@endforeach