routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\User;
use App\Permisos\Models\Role;
use App\Permisos\Models\Permission;
use Illuminate\Support\Facades\Gate;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
  if(Auth::guest())
    return view('auth.login');                   
  else
    return view('home');

});

Route::get('/remisiones', function () {
  return view('home_remisiones');
});


Auth::routes();

Route::get('/logout', function () {
  Auth::logout();
  return redirect('/');
});

Route::get('/home', 'HomeController@index')->name('home');


Route::resource('/role', 'RoleController')->names('role');

Route::resource('/remisiones/remisiones', 'RemisionesController')->names('remisiones');

Route::resource('/remisiones/clientes', 'ClientesRemisionController')->names('clientesRemisiones');
Route::resource('/remisiones/productos', 'ProductosRemisionController')->names('productosRemisiones');
Route::resource('/remisiones/conductores', 'ConductoresRemisionController')->names('conductoresRemisiones');
Route::resource('/remisiones/parametros', 'ParametrosRemisionController')->names('parametrosRemisiones');



Route::get('/remisiones/keyup/clientes/{valor?}', 'ClientesRemisionController@keyup_cliente');
Route::get('/remisiones/keyup/productos/{valor?}', 'ProductosRemisionController@keyup_producto');
Route::get('/remisiones/keyup/conductores/{valor?}', 'ConductoresRemisionController@keyup_conductores');

/* relleno de informacion en formulario remisiones segun cliente*/
Route::get('/remisiones/onchange/cliente/{valor?}', 'RemisionesController@onchange_cliente');

Route::get('/remisiones/onchange/producto_tabla/{valor?}', 'RemisionesController@onchange_productos');

Route::get('/remisiones/onchange/conductor/{atributo?}/{informacion?}', 'RemisionesController@onchange_conductor');

Route::get('/remisiones/remisiones/exportar/pdf/{atributo?}', 'RemisionesController@exportar_pdf')->name('remisiones.pdf');
Route::get('/remisiones/remisiones/imprimir/{atributo?}', 'RemisionesController@imprimir')->name('remisiones.imprimir');









/*

Route::get('/generate/csv/{fechaInicial?}/{fechaFinal?}/{conferencia?}/{asociado?}/{regional?}', 'ReportesController@exportCSVTodo');
Route::post('/reportes/exportTodoPdf', 'ReportesController@exportPDFTodo')->name('reportes.exportTodoPdf');

*/
Route::post('/reportes/generatemensajes', 'ReportesController@generatemensajes')->name('reportes.generatemensajes');
Route::post('/reportes/export/mensajes', 'ReportesController@exportMensajesCSV')->name('reportes.export.mensajes');
Route::post('/reportes/export/mensajespdf', 'ReportesController@exportMensajesPDF')->name('reportes.export.mensajespdf');




Route::resource('/user', 'UserController', ['except' => [
        'create', 'store']])->names('user');

app/Http/Controllers/RemisionesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use Barryvdh\DomPDF\Facade as PDF;

class RemisionesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $remisiones = DB::table('tabla_remisiones')
                    ->select('tabla_clientes_remisiones.*', 'tabla_conductor_remision.*', 'tabla_remisiones.*')
                    ->join('tabla_clientes_remisiones', 'tabla_remisiones.id_cliente', '=', 'tabla_clientes_remisiones.identificacion')
                    ->join('tabla_conductor_remision', 'tabla_remisiones.id_conductor_remision', '=', 'tabla_conductor_remision.identificacion_conductor')
                    ->where('estado', 1)
                    ->paginate(10);
        /*
        $remisiones = DB::table('tabla_detalle_descripcion_remisiones')
                    ->select('tabla_remisiones.*', 'tabla_descripcion_remisiones.*', 'tabla_clientes_remisiones.*', 'tabla_conductor_remision.*', 'tabla_productos_remisiones.*')
                    ->join('tabla_remisiones', 'tabla_detalle_descripcion_remisiones.id_remision_detalle', '=', 'tabla_remisiones.id_consecutivo')
                    ->join('tabla_descripcion_remisiones', 'tabla_detalle_descripcion_remisiones.id_descripcion_remisiones', '=', 'tabla_descripcion_remisiones.id_descripcion')
                    ->join('tabla_clientes_remisiones', 'tabla_remisiones.id_cliente', '=', 'tabla_clientes_remisiones.identificacion')
                    ->join('tabla_conductor_remision', 'tabla_remisiones.id_conductor_remision', '=', 'tabla_conductor_remision.identificacion_conductor')
                    ->join('tabla_productos_remisiones', 'tabla_descripcion_remisiones.id_producto', '=', 'tabla_productos_remisiones.id_producto')
                    ->paginate(10);
        */

        return view('remisiones.index', compact('remisiones'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $remisiones = DB::table('tabla_remisiones')->where('estado', 1)->orderby('id_consecutivo','DESC')->take(1)->get();

        if(count($remisiones) >= 1) {
            
            foreach ($remisiones as $remision) {
                $codigo_temporal = strlen($remision->id_consecutivo);
                if($codigo_temporal == "1"){
                    $codigo_remision = "00"+$remision->id_consecutivo+1;
                    $numero_remision = "00"+$codigo_remision;        
                } else if($codigo_temporal == "2"){
                    $codigo_remision = "0"+$remision->id_consecutivo+1;
                    $numero_remision = "0"+$codigo_remision;
                } else {
                    $codigo_remision = $remision->id_consecutivo+1;
                    $numero_remision = $codigo_remision;
                }
            }

        }else{
            $numero_remision = '001';
        }

    
        $clientes = DB::table('tabla_clientes_remisiones')->where('estado_cliente', 1)->get();
        $productos = DB::table('tabla_productos_remisiones')->where('estado_producto', 1)->get();
        $conductores = DB::table('tabla_conductor_remision')->where('estado_conductor', 1)->get();
        $parametros = DB::table('tabla_parametros_remision')->where('estado_parametro', 1)->get();
        $tipo_identificacion = DB::table('tabla_tipo_identificacion')->where('estado_tipo', 1)->get();

        return view('remisiones.crear', compact('numero_remision', 'clientes', 'productos', 'conductores', 'parametros', 'tipo_identificacion'));
    }

    public function onchange_cliente($identificacion){

        $informacion_cliente = [];

        $clientes = DB::table('tabla_clientes_remisiones')
        ->where('estado_cliente', 1)
        ->where('identificacion', $identificacion)->get();

        foreach ($clientes as $cliente) {
            $informacion_cliente[] = $cliente;
        }

        return $informacion_cliente;
    }

    public function onchange_productos($valor){

        $informacion_producto = [];

        $productos = DB::table('tabla_productos_remisiones')
        ->where('id_producto', $valor)
        ->where('estado_producto', 1)->get();

        foreach ($productos as $producto) {
            $informacion_producto[] = $producto;
        }

        return $informacion_producto;
    }


    public function onchange_conductor($atributo, $informacion){

        $informacion_conductor = [];

        if($atributo == 'placa'){
            $informacion_sql = DB::table('tabla_conductor_remision')
            ->where('identificacion_conductor', $informacion)->get();
            

            foreach ($informacion_sql as $info) {
                $informacion_conductor[] = $info;
            }

        }else{

            $informacion_sql = DB::table('tabla_conductor_remision')
            ->where('identificacion_conductor', $informacion)->get();

            foreach ($informacion_sql as $info) {
                $informacion_conductor[] = $info;
            }
        }

        return $informacion_conductor;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        //return $request->orden_remision;

        $request->validate([
            'codigo_remision' => 'required',
            'identificacion_cliente' => 'required',
            'fecha_remision' => 'required',
            'orden_remision' => 'required',
            'identificacion_conductor' => 'required'
        ]);
 

        $array_cantidad = ['hola'];
        $array_certificado = ['eliminar'];
        $array_certificado = ['eliminar'];
        $array_total_producto = ['eliminar'];


        foreach ($request->certificado_origen as $certificado) {
            $array_certificado[] = $certificado;    
        }
        unset($array_certificado[0]);


        foreach ($request->cantidad_producto as $cantidad) {
            $array_cantidad[] = $cantidad;    
        }
        unset($array_cantidad[0]);


        foreach ($request->total_producto as $total) {
            $array_total_producto[] = $total;    
        }
        unset($array_total_producto[0]);

        
        DB::table('tabla_remisiones')->insert([
            'id_consecutivo' => $request->codigo_remision,
            'id_cliente' => $request->identificacion_cliente,
            'fecha' => $request->fecha_remision,
            'vence' => $request->vence_remision,
            'orden' => $request->orden_remision,
            'id_conductor_remision' => $request->identificacion_conductor,
            'subtotal' => $request->subtotal_remision,
            'total' => $request->total_remision,
            'estado' => '1'
        ]);


        $i = 1;
        foreach ($request->codigo_producto as $producto) {
            $sum = $i++;
            if($producto != "0"){

                DB::table('tabla_descripcion_remisiones')->insert([
                    'id_producto' => $producto,
                    'certificado_de_origen' => $array_certificado[$sum],
                    'cantidad' => $array_cantidad[$sum],
                    'total' => $array_total_producto[$sum]
                ]);

                $tabla_detalle = DB::table('tabla_descripcion_remisiones')
                                    ->orderby('id_descripcion','DESC')->take(1)->get();

                foreach ($tabla_detalle as $valor) {
                    DB::table('tabla_detalle_descripcion_remisiones')->insert([
                        'id_remision_detalle' => $request->codigo_remision,
                        'id_descripcion_remisiones' => $valor->id_descripcion 
                    ]);
                }
                
            }else{
                
            }
        }

        return redirect()->route('remisiones.index')->with('status_success','Registro exitoso!'); 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $remision_unica = DB::table('tabla_remisiones')
                    ->select('tabla_clientes_remisiones.*', 'tabla_conductor_remision.*', 'tabla_remisiones.*')
                    ->join('tabla_clientes_remisiones', 'tabla_remisiones.id_cliente', '=', 'tabla_clientes_remisiones.identificacion')
                    ->join('tabla_conductor_remision', 'tabla_remisiones.id_conductor_remision', '=', 'tabla_conductor_remision.identificacion_conductor')
                    ->where('tabla_remisiones.id_consecutivo', $id)
                    ->paginate(10);

        $remisiones = DB::table('tabla_detalle_descripcion_remisiones')
                    ->select('tabla_remisiones.*', 'tabla_descripcion_remisiones.*', 'tabla_clientes_remisiones.*', 'tabla_conductor_remision.*', 'tabla_productos_remisiones.*')
                    ->join('tabla_remisiones', 'tabla_detalle_descripcion_remisiones.id_remision_detalle', '=', 'tabla_remisiones.id_consecutivo')
                    ->join('tabla_descripcion_remisiones', 'tabla_detalle_descripcion_remisiones.id_descripcion_remisiones', '=', 'tabla_descripcion_remisiones.id_descripcion')
                    ->join('tabla_clientes_remisiones', 'tabla_remisiones.id_cliente', '=', 'tabla_clientes_remisiones.identificacion')
                    ->join('tabla_conductor_remision', 'tabla_remisiones.id_conductor_remision', '=', 'tabla_conductor_remision.identificacion_conductor')
                    ->join('tabla_productos_remisiones', 'tabla_descripcion_remisiones.id_producto', '=', 'tabla_productos_remisiones.id_producto')
                    ->where('tabla_remisiones.id_consecutivo', $id)
                    ->paginate(10);

resources/views/remisiones/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content " >
    <div class="container-fluid" style="background-color: white; padding-top: 10px;">
        <div class="row">
            <div class="col-md-12">
              <div class="card card-plain">
                <div class="card-header card-header-primary">
                  <h3 class="card-title mt-0">Modulo de remisiones</h3>
                  <p class="card-category"></p>
                </div>
                <div class="card-body">
                    @include('custom.message')
                  <div class="table-responsive">
                    <div class="form-group">
                        <label><b>Búsqueda de remisiones...</b></label>
                        <input type="text" class="form-control" id="busqueda_conductores" name="busqueda_conductores" placeholder="Digite nombre, apellido o placa del conductor a buscar">
                    </div>
                    <hr style="margin-top: 10px; margin-bottom: 20px;">
                    <table class="table table-hover table-bordered" id="resultado_consulta">
                        <thead>
                            <tr>
                                <th scope="col"><b>Remisi&oacute;n No.</b></th>
                                <th scope="col"><b>Orden de la Remisi&oacute;n</b></th>
                                <th scope="col"><b>Nombres y apellidos del cliente</b></th>
                                <th scope="col"><b>Nombres y apellidos del conductor</b></th>
                                <th scope="col"><b>Fecha registro</b></th>
                                <th scope="col" style="text-align: center;" colspan="2"><b>Acciones</b></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $i=1; ?>
                             @foreach($remisiones as $remision)
                             	<tr>
                             		<td>{{ $remision->id_consecutivo }}</td>
                             		<td>
                             			{{ $remision->orden }}
                             		</td>
                             		<td>
                             			{{ $remision->nombres_cliente }} {{ $remision->apellidos_cliente }}
                             		</td>
                             		<td>
                             			{{ $remision->nombres_conductor }} {{ $remision->apellidos_conductor }}
                             		</td>
                             		<td>
                             			{{ $remision->fecha }}
                             		</td>
                             		<td style="text-align: center;">
	                                    <button type="button" class="btn btn-info btnVer" title="Ver registro" data-id="{{ $remision->id_consecutivo }}" data-url="{{ route('remisiones.show', $remision->id_consecutivo ) }}"><i class="fas fa-eye"></i></button>
                                        <a href="{{ route('remisiones.edit', $remision->id_consecutivo ) }}">
	                                    <button type="button" class="btn btn-success" title="Editar registro" data-id="{{ $remision->id_consecutivo }}" data-url=""><i class="far fa-edit"></i></button></a>
                                        
                                	</td>
                                    <td>
                                        <a href="{{ route('remisiones.pdf', $remision->id_consecutivo ) }}">
                                            <button type="button" class="btn btn-danger" title="Exportar a PDF"><i class="fas fa-file-pdf"></i></button>
                                        </a>
                                        <!--
                                        <button type="button" class="btn btn-success btnEdicion" title="Exportar a EXCEL" data-id="{{ $remision->id_consecutivo }}" data-url="{{ route('remisiones.edit', $remision->id_consecutivo ) }}"><i class="fas fa-file-excel"></i></button>-->
                                        <button type="button" class="btn btn-info imprimir" title="Imprimir" data-id="{{ $remision->id_consecutivo }}" data-url="{{ route('remisiones.imprimir', $remision->id_consecutivo ) }}"><i class="fas fa-print"></i></button>
                                    </td>
                                <td>
                                    <center>
                                    <form method="POST" action="{{ route('remisiones.destroy', $remision->id_consecutivo)}}">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-warning" title="Eliminar registro">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </form>
                                    </center>
                                </td>
                             	</tr>
                             @endforeach
                        </tbody>
                    </table>

                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/remisiones/show.blade.php
<div class="container">
	 @include('custom.parameters')
</div>
@foreach($remision_unica as $remision_uni)
	<div class="container">
		<div class="table-responsive">
			<!-- NUMERO DE REMISION -->
			<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
				<div class="row">
					<div class="col-12 col-sm-7 col-md-7 col-lg-7" style="text-align: center;"></div>
					<div class="col-12 col-sm-5 col-md-5 col-lg-5">
						<div class="form-group row">
							<label for="staticEmail" class="col-sm-6 col-form-label">
								<b>REMISION No.</b>
							</label>
							<div class="col-sm-6">
								<input type="number" name="codigo_remision" class="form-control" id="staticEmail" value="{{ $remision_uni->id_consecutivo }}" disabled="" />
							</div>
						</div>
					</div>
				</div>
			</div>

			<!-- CLIENTE Y FECHA -->
			<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
				<div class="row">

					<div class="col-12 col-sm-7 col-md-7 col-lg-7" style="padding-top:30px; border: 1px solid black; border-radius: 15px;">
						<center>
							<h4><b>Informaci&oacute;n del cliente</b></h4>
						</center>
						<br>
						<div class="form-group row">
							<label for="staticEmail" class="col-sm-2 col-form-label">
								<b>Nombre</b>
							</label>
							<div class="col-sm-10">
								<input type="text" class="form-control" disabled="" value="{{ $remision_uni->nombres_cliente }}">		
							</div>
						</div>
						<div class="form-group row">
							<label for="staticEmail" class="col-sm-2 col-form-label">
								<b>Nit. / C.C</b>
							</label>
							<div class="col-sm-10">
								<input type="text" class="form-control" id="identificacion_formulario" value="{{ $remision_uni->identificacion }}" disabled="" />
							</div>
						</div>
						<div class="form-group row">
							<label for="staticEmail" class="col-sm-2 col-form-label">
								<b>Direccion:</b>
							</label>
							<div class="col-sm-10">
								<input type="text" class="form-control" id="direccion_formulario" value="{{ $remision_uni->direccion_cliente }}" disabled="" />
							</div>
						</div>
						<div class="form-group row">
							<label for="staticEmail" class="col-sm-2 col-form-label">
								<b>Ciudad:</b>
							</label>
							<div class="col-sm-10">
								<input type="text" class="form-control" id="ciudad_formulario" value="{{ $remision_uni->ciudad_cliente }}" disabled="" />
							</div>
						</div>
						<div class="form-group row">
							<label for="staticEmail" class="col-sm-2 col-form-label">
								<b>Telefono:</b>
							</label>
							<div class="col-sm-10">
								<input type="text" class="form-control" id="telefono_formulario" value="{{ $remision_uni->telefono_fijo_cliente }} - {{ $remision_uni->celular_1_cliente }} - {{ $remision_uni->celular_2_cliente }}" disabled="" />
							</div>
						</div>
						<div class="form-group row">
							<label for="staticEmail" class="col-sm-2 col-form-label">
								<b>Email:</b>
							</label>
							<div class="col-sm-10">
								<input type="email" class="form-control" id="email_formulario" value="{{ $remision_uni->email_cliente }}" disabled="" />
							</div>
						</div>
					</div>
					<div class="col-12 col-sm-5 col-md-5 col-lg-5" style=" padding-top:30px; text-align: center; border: 1px solid black; border-radius: 15px; ">
						<div class="form-group row">
							<label for="staticEmail" class="col-sm-2 col-form-label">
								<b>FECHA</b>
							</label>
							<div class="col-sm-10">
								<input type="text" class="form-control" name="fecha_remision" value="{{ $remision_uni->fecha }}" disabled="" />
							</div>
						</div>
						<div class="form-group row">
							<label for="staticEmail" class="col-sm-2 col-form-label">
								<b>Vence</b>
							</label>
							<div class="col-sm-10">
								<input type="text" class="form-control-plaintext" name="vence_remision" value="{{ $remision_uni->vence }}" disabled="" />
							</div>
						</div>
						<div class="form-group row">
							<label for="staticEmail" class="col-sm-2 col-form-label">
								<b>Orden:</b>
							</label>
							<div class="col-sm-10">
								<input type="text" class="form-control" name="orden_remision" value="{{ $remision_uni->orden }}" disabled="" />
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
@endforeach
			

<div class="container">
	<!-- PRODUCTOS -->
	<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
		<div class="row">
			<div class="col-12 col-sm-12 col-md-12 col-lg-12" style="padding-top:30px; border: 1px solid black; border-radius: 15px;">
				<center>
					<h4><b>Informaci&oacute;n de los productos</b></h4>
				</center>
				<table id="lista_productos" class="table table-bordered table-responsive">
					<thead>
						<tr>
							<th>C&oacute;digo del producto</th>
							<th>Descripci&oacute;n</th>
							<th>Certificado de origen</th>
							<th>Cantidad</th>
							<th>Total</th>
						</tr>
					</thead>
					<tbody>
						@foreach($remisiones as $remision)
							<tr>
								<td>
									<input type="text" name="" value="{{ $remision->id_producto }}" disabled="">
								</td>
								<td>
									<input type="text" name="" value="{{ $remision->descripcion_producto }}" disabled="">
								</td>
								<td>
									<input type="text" name="" value="{{ $remision->certificado_de_origen }}" disabled="">
								</td>
								<td>
									<input type="text" name="" value="{{ $remision->cantidad }}" disabled="">
								</td>
								<td>
									<input type="text" name="" value="{{ $remision->total }}" disabled="">
								</td>
							</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<div class="container">
	<!-- VALORES -->
	<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
		<div class="row">
			<div class="col-12 col-sm-7 col-md-7 col-lg-7" style="padding-top:30px; border: 1px solid black; border-radius: 15px;">
				<div class="form-group row">
					<label for="staticEmail" class="col-sm-2 col-form-label">
						<b>Son:</b>
					</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" name="son_remision"disabled="">
					</div>
				</div>
				<div class="form-group row">
					<label for="staticEmail" class="col-sm-2 col-form-label">
						<b>Comentarios</b>
					</label>
					<div class="col-sm-10">
						<textarea class="form-control" name="comentarios_remision"disabled=""></textarea>
					</div>
				</div>
			</div>
			<div class="col-12 col-sm-5 col-md-5 col-lg-5" style="padding-top:30px; text-align: center; border: 1px solid black; border-radius: 15px; ">
				<div class="form-group row">
					<label for="staticEmail" class="col-sm-2 col-form-label">
						<b>Subtotal</b>
					</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" name="subtotal_remision" disabled=""/>
					</div>
				</div>
				<div class="form-group row">
					<label for="staticEmail" class="col-sm-2 col-form-label">
						<b>TOTAL</b>
					</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" name="total_remision" disabled=""/>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<div class="container">
	<!-- CONDUCTOR -->
	<div class="form-group col-12 col-sm-12 col-md-12 col-lg-12">
		<div class="row">
			<div class="col-12 col-sm-12 col-md-12 col-lg-12" style="padding-top:30px; border: 1px solid black; border-radius: 15px;">
				<center>
					<h4><b>Informaci&oacute;n del conductor</b></h4>
				</center>
				<table id="lista_productos" class="table table-bordered table-responsive">
					<thead>
						<tr>
							<th>Placa del vehiculo</th>
							<th>Identificacion del conductor</th>
							<th>Nombre del conductor</th>
							<th>Celular conductor</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							@foreach($remision_unica as $remision_uni)
								<td>
									<input type="text" name="" disabled="" value="{{ $remision_uni->placa_conductor }}">
								</td>
								<td>
									<input type="text" name="" disabled="" value="{{ $remision_uni->identificacion_conductor }}">
								</td>
								<td>
									<input type="text" name="" disabled="" value="{{ $remision_uni->nombres_conductor }} {{ $remision_uni->apellidos_conductor }}">
								</td>
								<td>
									<input type="text" name="" disabled="" value="{{ $remision_uni->celular_1_conductor }} {{ $remision_uni->celular_2_conductor }}">
								</td>
							@endforeach
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>