routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\User;
use App\Permisos\Models\Role;
use App\Permisos\Models\Permission;
use Illuminate\Support\Facades\Gate;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
  if(Auth::guest())
    return view('auth.login');                   
  else
    return view('home');

});

Route::get('/remisiones', function () {
  return view('home_remisiones');
});


Auth::routes();

Route::get('/logout', function () {
  Auth::logout();
  return redirect('/');
});

Route::get('/home', 'HomeController@index')->name('home');


Route::resource('/role', 'RoleController')->names('role');

Route::resource('/remisiones/remisiones', 'RemisionesController')->names('remisiones');

Route::resource('/remisiones/clientes', 'ClientesRemisionController')->names('clientesRemisiones');
Route::resource('/remisiones/productos', 'ProductosRemisionController')->names('productosRemisiones');
Route::resource('/remisiones/conductores', 'ConductoresRemisionController')->names('conductoresRemisiones');
Route::resource('/remisiones/parametros', 'ParametrosRemisionController')->names('parametrosRemisiones');



Route::get('/remisiones/keyup/clientes/{valor?}', 'ClientesRemisionController@keyup_cliente');
Route::get('/remisiones/keyup/productos/{valor?}', 'ProductosRemisionController@keyup_producto');
Route::get('/remisiones/keyup/conductores/{valor?}', 'ConductoresRemisionController@keyup_conductores');

/* relleno de informacion en formulario remisiones segun cliente*/
Route::get('/remisiones/onchange/cliente/{valor?}', 'RemisionesController@onchange_cliente');

Route::get('/remisiones/onchange/producto_tabla/{valor?}', 'RemisionesController@onchange_productos');

Route::get('/remisiones/onchange/conductor/{atributo?}/{informacion?}', 'RemisionesController@onchange_conductor');

Route::get('/remisiones/remisiones/exportar/pdf/{atributo?}', 'RemisionesController@exportar_pdf')->name('remisiones.pdf');
Route::get('/remisiones/remisiones/imprimir/{atributo?}', 'RemisionesController@imprimir')->name('remisiones.imprimir');









/*

Route::get('/generate/csv/{fechaInicial?}/{fechaFinal?}/{conferencia?}/{asociado?}/{regional?}', 'ReportesController@exportCSVTodo');
Route::post('/reportes/exportTodoPdf', 'ReportesController@exportPDFTodo')->name('reportes.exportTodoPdf');

*/
Route::post('/reportes/generatemensajes', 'ReportesController@generatemensajes')->name('reportes.generatemensajes');
Route::post('/reportes/export/mensajes', 'ReportesController@exportMensajesCSV')->name('reportes.export.mensajes');
Route::post('/reportes/export/mensajespdf', 'ReportesController@exportMensajesPDF')->name('reportes.export.mensajespdf');




Route::resource('/user', 'UserController', ['except' => [
        'create', 'store']])->names('user');

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Permisos\Models\Role;
use App\Permisos\Models\Permission;
use Illuminate\Support\Facades\Gate;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Gate::authorize('haveaccess','role.index');

        $roles =  Role::orderBy('id','Asc')->paginate(10);

        return view('role.index',compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Gate::authorize('haveaccess','role.create');

        $permissions = Permission::get();

        return view('role.create', compact('permissions'));


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Gate::authorize('haveaccess','role.create');

        $request->validate([
            'name'          => 'required|max:50|unique:roles,name',
            'slug'          => 'required|max:50|unique:roles,slug',
            'full-access'   => 'required|in:yes,no'
        ]);

        $role = Role::create($request->all());
        
        //if ($request->get('permission')) {
            //return $request->all();
            $role->permissions()->sync($request->get('permission'));
        //}
        return redirect()->route('role.index')
            ->with('status_success','Creación exitosa!'); 
       
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        $this->authorize('haveaccess','role.show');

        $permission_role=[];

        foreach($role->permissions as $permission) {
            $permission_role[]=$permission->id; 
        }
        //return   $permission_role;


        //return $role;
        $permissions = Permission::get();




        return view('role.view', compact('permissions','role','permission_role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {   

        $this->authorize('haveaccess','role.edit');
        $permission_role=[];

        foreach($role->permissions as $permission) {
            $permission_role[]=$permission->id; 
        }
        //return   $permission_role;


        //return $role;
        $permissions = Permission::get();




        return view('role.edit', compact('permissions','role','permission_role'));
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $this->authorize('haveaccess','role.edit');
        $request->validate([
            'name'          => 'required|max:50|unique:roles,name,'.$role->id,
            'slug'          => 'required|max:50|unique:roles,slug,'.$role->id,
            'full-access'   => 'required|in:yes,no'
        ]);

        $role->update($request->all());
        
        //if ($request->get('permission')) {
            //return $request->all();
            $role->permissions()->sync($request->get('permission'));
        //}
        return redirect()->route('role.index')
            ->with('status_success','Rol actualizado exitosamente!'); 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {   
        $this->authorize('haveaccess','role.destroy');
        $role->delete();

        return redirect()->route('role.index')
            ->with('status_success','Rol eliminado'); 
        
    }
}

resources/views/role/create.blade.php
@extends('layouts.app')

@section('content')

<div class="content">
  <div class="container-fluid" style="background-color: white; padding-top: 10px;">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-plain">
          <div class="card-header card-header-primary">
            <h3 class="card-title mt-0">Registrar un Rol en el Sistema</h3>
          </div>

          <div class="card-body">
            @include('custom.message')
            <div class="table-responsive">
              <form action="{{ route('role.store')}}" method="POST">
                @csrf

                <h3><b>Información requerida</b></h3>

                <div class="form-group">
                  <input type="text" class="form-control" id="name" placeholder="Name" name="name" value="{{ old('name')}}" />
                </div>

                <div class="form-group">
                  <input type="text" class="form-control" id="slug" placeholder="Slug" name="slug" value="{{ old('slug')}}" />
                </div>

                <div class="form-group">
                  <textarea class="form-control" placeholder="Description" name="description" id="description" rows="3"> 
                    {{ old('description')}}
                  </textarea>
                </div>

                <h3><b>¿Conceder acceso administrativo?</b></h3>

                <div class="custom-control custom-radio custom-control-inline">
                  <input type="radio" id="fullaccessyes" name="full-access" class="custom-control-input" value="yes"
                            @if (old('full-access')=="yes") 
                              checked 
                            @endif
                  />
                  <label class="custom-control-label" for="fullaccessyes">Si</label>
                </div>

                <div class="custom-control custom-radio custom-control-inline">
                  <input type="radio" id="fullaccessno" name="full-access" class="custom-control-input" value="no" 
                            @if (old('full-access')=="no") 
                              checked 
                            @endif
                            @if (old('full-access')===null) 
                              checked 
                            @endif
                  />
                  <label class="custom-control-label" for="fullaccessno">No</label>
                </div>

                <h3><b>Listado de Permisos</b></h3>

                @foreach($permissions as $permission)

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" id="permission_{{$permission->id}}" value="{{$permission->id}}" name="permission[]"
                    @if( is_array(old('permission')) && in_array("$permission->id", old('permission'))    )
                      checked
                    @endif
                  />

                  <label class="custom-control-label" for="permission_{{$permission->id}}">
                    {{ $permission->id }}
                    - 
                    {{ $permission->name }} 
                    <em>( {{ $permission->description }} )</em>
                  </label>
                </div>

                @endforeach

                <center>
                  <a href="{{route('role.index')}}">
                    <button class="btn btn-danger" type="button">
                      <i class="material-icons">keyboard_backspace</i> Regresar
                    </button>
                  </a>

                  <button class="btn btn-primary" type="submit">
                    <i class="material-icons">how_to_reg</i> Registrar
                  </button>
                </center>
              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/role/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="content " >
    <div class="container-fluid" style="background-color: white; padding-top: 10px;">
        <div class="row">
            <div class="col-md-12">
              <div class="card card-plain">
                <div class="card-header card-header-primary">
                  <h3 class="card-title mt-0">Edición rol seleccionado</h3>
                  <!-- <p class="card-category">Acá puede ver todos los roles registrados en el sistema</p> -->
                </div>

                <div class="card-body">
                    @include('custom.message')
                    <div class="table-responsive">
                      <form action="{{ route('role.update', $role->id)}}" method="POST">
                        @csrf
                        @method('PUT')

                         <div class="form-group">                            
                            <input type="text" class="form-control" 
                            id="name" 
                            placeholder="Nombre"
                            name="name"
                            value="{{ old('name', $role->name)}}"
                            >
                          </div>
                          <div class="form-group">                            
                            <input type="text" 
                            class="form-control" 
                            id="slug" 
                            placeholder="Slug"
                            name="slug"
                            value="{{ old('slug' , $role->slug)}}"
                            >
                          </div>

                          <div class="form-group">
                            
                            <textarea class="form-control" placeholder="Descripción" name="description" id="description" rows="3">{{old('description', $role->description)}}</textarea>
                          </div>

                          <hr>

                          <h3>Acceso de administrador</h3>
                          <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" id="fullaccessyes" name="full-access" class="custom-control-input" value="yes"
                            @if ( $role['full-access']=="yes") 
                              checked 
                            @elseif (old('full-access')=="yes") 
                              checked 
                            @endif
                            
                            
                            >
                            <label class="custom-control-label" for="fullaccessyes">Acceso total</label>
                          </div>
                          <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" id="fullaccessno" name="full-access" class="custom-control-input" value="no" 
                            
                            @if ( $role['full-access']=="no") 
                              checked 
                            @elseif (old('full-access')=="no") 
                              checked 
                            @endif
                            
                            
                            >
                            <label class="custom-control-label" for="fullaccessno">Acceso Personalizado</label>
                          </div>

                          <hr>


                          <h3>Permisos del sistema</h3>


                          @foreach($permissions as $permission)

                          
                          <div class="custom-control custom-checkbox">
                            <input type="checkbox" 
                            class="custom-control-input" 
                            id="permission_{{$permission->id}}"
                            value="{{$permission->id}}"
                            name="permission[]"

                            @if( is_array(old('permission')) && in_array("$permission->id", old('permission'))    )
                            checked

                            @elseif( is_array($permission_role) && in_array("$permission->id", $permission_role)    )
                            checked

                            @endif
                            >
                            <label class="custom-control-label" 
                                for="permission_{{$permission->id}}">
                                {{ $permission->id }}
                                - 
                                {{ $permission->name }} 
                                <em>( {{ $permission->description }} )</em>
                            
                            </label>
                          </div>


                          @endforeach
                          <hr>
                          <center>

                            <a href="{{route('role.index')}}">
                              <button class="btn btn-danger" type="button">
                                <i class="material-icons">keyboard_backspace</i> Regresar
                              </button>
                            </a>

                            <button class="btn btn-primary" type="submit">
                              <i class="material-icons">update</i> Actualizar
                            </button>
                            
                          </center>

                     </div>
                   </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/role/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content " >
    <div class="container-fluid" style="background-color: white; padding-top: 10px;">
        <div class="row">
            <div class="col-md-12">
              <div class="card card-plain">
                <div class="card-header card-header-primary">
                  <h3 class="card-title mt-0">Modulo de Roles</h3>
                  <p class="card-category">Acá puede ver todos los roles registrados en el sistema</p>
                </div>

                <div class="card-body">
                    @include('custom.message')
                  <div class="table-responsive">
                    @can('haveaccess','role.create')
                    <a href="{{route('role.create')}}" 
                       class="btn btn-primary float-right"
                       >Crear rol
                    </a>
                    <br><br>
                    @endcan
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col"><b>Nombre</b></th>
                                <th scope="col"><b>Slug</b></th>
                                <th scope="col"><b>Descripción</b></th>
                                <th scope="col"><b>¿Acceso total?</b></th>
                                <th colspan="3" style="text-align: center;"><b>Acciones</b></th>
                            </tr>
                        </thead>
                        <tbody>


                            @foreach ($roles as $role)
                            <tr>
                                <th scope="row">{{ $role->id}}</th>
                                <td>{{ $role->name}}</td>
                                <td>{{ $role->slug}}</td>
                                <td>{{ $role->description}}</td>
                                <td>{{ $role['full-access']}}</td>                            
                                <td> 
                                    @can('haveaccess','role.show')
                                    <a class="btn btn-info" href="{{ route('role.show',$role->id)}}">
                                        <i class="material-icons">visibility</i>
                                    </a> 
                                    @endcan 
                                </td>  
                                <td> 
                                    @can('haveaccess','role.edit')
                                    <a class="btn btn-success" href="{{ route('role.edit',$role->id)}}">
                                        <i class="material-icons">create</i>
                                    </a> 
                                    @endcan
                                </td>  

                                <td> 
                                    @can('haveaccess','role.destroy')
                                    <form action="{{ route('role.destroy',$role->id)}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger">
                                            <i class="material-icons">delete_forever</i>
                                        </button>
                                    </form>
                                    @endcan

                                </td>  
                            </tr>      
                            @endforeach

                        </tbody>
                    </table>

                    {{ $roles->links() }}

                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/role/view.blade.php
@extends('layouts.app')

@section('content')
<div class="content " >
    <div class="container-fluid" style="background-color: white; padding-top: 10px;">
        <div class="row">
            <div class="col-md-12">
              <div class="card card-plain">
                <div class="card-header card-header-primary">
                  <h3 class="card-title mt-0">Edición rol seleccionado</h3>
                  <!-- <p class="card-category">Acá puede ver todos los roles registrados en el sistema</p> -->
                </div>

                <div class="card-body">
                    @include('custom.message')
                  <div class="table-responsive">
                    <form action="{{ route('role.update', $role->id)}}" method="POST">
                     @csrf
                     @method('PUT')

                     <div class="form-group">                            
                      <input type="text" class="form-control" id="name" placeholder="Name" name="name" value="{{ old('name', $role->name)}}" readonly />
                     </div>

                    <div class="form-group">
                      <input type="text" class="form-control" id="slug" placeholder="Slug"name="slug"value="{{ old('slug' , $role->slug)}}"readonly />
                    </div>

                    <div class="form-group">
                      <textarea  readonly class="form-control" placeholder="Description" name="description" id="description" rows="3">{{old('description', $role->description)}}</textarea>
                    </div>

                    <hr>

                    <h3><b>Acceso administrativo</b></h3>

                    <div class="custom-control custom-radio custom-control-inline">

                      <input disabled type="radio" id="fullaccessyes" name="full-access" class="custom-control-input" value="yes"
                            @if ( $role['full-access']=="yes") 
                              checked 
                            @elseif (old('full-access')=="yes") 
                              checked 
                            @endif
                      />

                      <label class="custom-control-label" for="fullaccessyes">Si</label>
                    </div>

                    <div class="custom-control custom-radio custom-control-inline">
                      <input disabled type="radio" id="fullaccessno" name="full-access" class="custom-control-input" value="no" 
                            
                            @if ( $role['full-access']=="no") 
                              checked 
                            @elseif (old('full-access')=="no") 
                              checked 
                            @endif
                      />
                      <label class="custom-control-label" for="fullaccessno">Acceso personalizado</label>
                    </div>

                    <hr>

                    <h3><b>Permisos asignados</b></h3>

                    @foreach($permissions as $permission)

                    <div class="custom-control custom-checkbox">
                      <input type="checkbox" 
                            disabled
                            class="custom-control-input" 
                            id="permission_{{$permission->id}}"
                            value="{{$permission->id}}"
                            name="permission[]"

                            @if( is_array(old('permission')) && in_array("$permission->id", old('permission'))    )
                            checked

                            @elseif( is_array($permission_role) && in_array("$permission->id", $permission_role)    )
                            checked

                            @endif
                      />

                      <label class="custom-control-label" 
                        for="permission_{{$permission->id}}">
                                {{ $permission->id }}
                                - 
                                {{ $permission->name }} 
                              </label>
                      </div>
                      @endforeach

                      <hr>
                      <div style="text-align: center;">
                        <a class="btn btn-danger" href="{{route('role.index')}}"><i class="material-icons">keyboard_backspace</i> Regresar</a>
                        <a class="btn btn-success" href="{{route('role.edit',$role->id)}}"><i class="material-icons">create</i> Editar</a>
                      </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>

@endsection