routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\User;
use App\Permisos\Models\Role;
use App\Permisos\Models\Permission;
use Illuminate\Support\Facades\Gate;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
  if(Auth::guest())
    return view('auth.login');                   
  else
    return view('home');

});

Route::get('/remisiones', function () {
  return view('home_remisiones');
});


Auth::routes();

Route::get('/logout', function () {
  Auth::logout();
  return redirect('/');
});

Route::get('/home', 'HomeController@index')->name('home');


Route::resource('/role', 'RoleController')->names('role');

Route::resource('/remisiones/remisiones', 'RemisionesController')->names('remisiones');

Route::resource('/remisiones/clientes', 'ClientesRemisionController')->names('clientesRemisiones');
Route::resource('/remisiones/productos', 'ProductosRemisionController')->names('productosRemisiones');
Route::resource('/remisiones/conductores', 'ConductoresRemisionController')->names('conductoresRemisiones');
Route::resource('/remisiones/parametros', 'ParametrosRemisionController')->names('parametrosRemisiones');



Route::get('/remisiones/keyup/clientes/{valor?}', 'ClientesRemisionController@keyup_cliente');
Route::get('/remisiones/keyup/productos/{valor?}', 'ProductosRemisionController@keyup_producto');
Route::get('/remisiones/keyup/conductores/{valor?}', 'ConductoresRemisionController@keyup_conductores');

/* relleno de informacion en formulario remisiones segun cliente*/
Route::get('/remisiones/onchange/cliente/{valor?}', 'RemisionesController@onchange_cliente');

Route::get('/remisiones/onchange/producto_tabla/{valor?}', 'RemisionesController@onchange_productos');

Route::get('/remisiones/onchange/conductor/{atributo?}/{informacion?}', 'RemisionesController@onchange_conductor');

Route::get('/remisiones/remisiones/exportar/pdf/{atributo?}', 'RemisionesController@exportar_pdf')->name('remisiones.pdf');
Route::get('/remisiones/remisiones/imprimir/{atributo?}', 'RemisionesController@imprimir')->name('remisiones.imprimir');









/*

Route::get('/generate/csv/{fechaInicial?}/{fechaFinal?}/{conferencia?}/{asociado?}/{regional?}', 'ReportesController@exportCSVTodo');
Route::post('/reportes/exportTodoPdf', 'ReportesController@exportPDFTodo')->name('reportes.exportTodoPdf');

*/
Route::post('/reportes/generatemensajes', 'ReportesController@generatemensajes')->name('reportes.generatemensajes');
Route::post('/reportes/export/mensajes', 'ReportesController@exportMensajesCSV')->name('reportes.export.mensajes');
Route::post('/reportes/export/mensajespdf', 'ReportesController@exportMensajesPDF')->name('reportes.export.mensajespdf');




Route::resource('/user', 'UserController', ['except' => [
        'create', 'store']])->names('user');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Permisos\Traits\UserTrait;

class User extends Authenticatable
{
    use Notifiable, UserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    

   
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Permisos\Models\Role;
use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('haveaccess','user.index');
        $users =  User::with('roles')->orderBy('id','asc')->paginate(10);
        //return $users; 

        return view('user.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //$this->authorize('create', User::class);
        //return 'Create';
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $this->authorize('view', [$user, ['user.show','userown.show'] ]);
        $roles= Role::orderBy('name')->get();

        //return $roles;

        return view('user.view', compact('roles', 'user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $this->authorize('update', [$user, ['user.edit','userown.edit'] ]);
        $roles= Role::orderBy('name')->get();

        //return $roles;

        return view('user.edit', compact('roles', 'user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'name'          => 'required|max:50|unique:users,name,'.$user->id,
            'email'         => 'required|max:50|unique:users,email,'.$user->id            
        ]);

        //dd($request->all());

        $user->update($request->all());

        $user->roles()->sync($request->get('roles'));
        
        return redirect()->route('user.index')
            ->with('status_success','Actualización exitosa!'); 



    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $this->authorize('haveaccess','user.destroy');
        $user->delete();

        return redirect()->route('user.index')
            ->with('status_success','Usuario eliminado'); 
    }
}

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="content " >
    <div class="container-fluid" style="background-color: white; padding-top: 10px;">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
              <div class="card card-plain">
                <div class="card-header card-header-primary">
                  <h2 class="card-title mt-0">Edicion de usuario</h2>
                  <!--<p class="card-category">Acá puede ver todos los usuarios registrados en el sistema</p>-->
                </div>
                <div class="card-body">
                    @include('custom.message')
                  <div class="table-responsive">
                    <form action="{{ route('user.update', $user->id)}}" method="POST">
                      @csrf
                      @method('PUT')
                      <div class="form-group">
                        <input type="text" class="form-control" id="name" placeholder="Name" name="name" value="{{ old('name', $user->name)}}" />
                      </div>
                      <div class="form-group">                            
                        <input type="text" class="form-control" id="email" placeholder="email" name="email" value="{{ old('email' , $user->email)}}" />
                      </div>
                      <div class="form-group">
                        <select  class="form-control"  name="roles" id="roles">
                          @foreach($roles as $role)
                            <option value="{{ $role->id }}"
                              @isset($user->roles[0]->name)
                              @if($role->name ==  $user->roles[0]->name)
                                selected
                              @endif
                              @endisset
                              >
                              {{ $role->name }}
                            </option>
                          @endforeach
                        </select>
                      </div>

                      <br><br>
                      <center>

                        <a href="{{route('user.index')}}">
                          <button class="btn btn-danger" type="button">
                            <i class="material-icons">keyboard_backspace</i> Regresar
                          </button>
                        </a>

                        <button class="btn btn-primary" type="submit">
                          <i class="material-icons">update</i> Actualizar
                        </button>
                        
                      </center>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="content " >
    <div class="container-fluid" style="background-color: white; padding-top: 10px;">
        <div class="row">
            <div class="col-md-12">
              <div class="card card-plain">
                <div class="card-header card-header-primary">
                  <h3 class="card-title mt-0">Modulo de usuarios</h3>
                  <p class="card-category">Acá puede ver todos los usuarios registrados en el sistema</p>
                </div>
                <div class="card-body">
                    @include('custom.message')
                  <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col"><b>Nombre</b></th>
                                <th scope="col"><b>Correo</b></th>
                                <th scope="col"><b>Rol(es)</b></th>
                                <th colspan="3" style="text-align: center;"><b>Acciones</b></th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach ($users as $user)

                            <tr>
                                <th scope="row">{{ $user->id}}</th>
                                <td>{{ $user->name}}</td>
                                <td>{{ $user->email}}</td>
                                <td>
                                    @isset( $user->roles[0]->name )
                                    {{ $user->roles[0]->name}}
                                    @endisset

                                </td>
                                <td> 
                                    
                                </td>  
                                <td> 
                                    @can('view', [$user, ['user.edit','userown.edit'] ])
                                    <a class="btn btn-success" href="{{ route('user.edit',$user->id)}}">
                                        <i class="material-icons">create</i>
                                    </a> 
                                    @endcan
                                </td>  
                                <td> 
                                    @can('haveaccess','user.destroy')
                                    <form action="{{ route('user.destroy',$user->id)}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger">
                                            <i class="material-icons">delete_forever</i>
                                        </button>
                                    </form>
                                    @endcan
                                </td>  
                            </tr>      
                            @endforeach
                        </tbody>
                    </table>
                    {{ $users->links() }}

                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/user/view.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h2>Detalle del usuario</h2></div>

                <div class="card-body">
                    @include('custom.message')
                    <form action="{{ route('user.update', $user->id)}}" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="container">
                            <div class="form-group">                            
                                <input type="text" class="form-control" 
                                       id="name" 
                                       placeholder="Name"
                                       name="name"
                                       value="{{ old('name', $user->name)}}"
                                       disabled>
                            </div>
                            <div class="form-group">                            
                                <input type="text" 
                                       class="form-control" 
                                       id="email" 
                                       placeholder="email"
                                       name="email"
                                       value="{{ old('email' , $user->email)}}"
                                       disabled>
                            </div>

                            <div class="form-group">                            
                                <select disabled class="form-control"  name="roles" id="roles">
                                    @foreach($roles as $role)
                                    <option value="{{ $role->id }}"
                                            @isset($user->roles[0]->name)
                                            @if($role->name ==  $user->roles[0]->name)
                                            selected
                                            @endif
                                            @endisset


                                            >{{ $role->name }}</option>
                                    @endforeach
                                </select>
                            </div>


                            <hr>

                            <a class="btn btn-success" href="{{route('user.edit',$user->id)}}">Editar</a>
                            <a class="btn btn-danger" href="{{route('user.index')}}">Regresar</a>

                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection